CREATE TABLE IF NOT EXISTS public.api_tokens
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint              NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name         varchar(255)        NOT NULL,
    token_hash   varchar(255) UNIQUE NOT NULL,
    abilities    json                NULL,
    last_used_at timestamptz,
    created_at   timestamptz DEFAULT now(),
    updated_at   timestamptz DEFAULT now()
);

CREATE INDEX idx_api_tokens_token_hash ON api_tokens (token_hash);