CREATE TABLE IF NOT EXISTS public.users
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             varchar(255)               NOT NULL,
    email_verified_at timestamptz,
    password          varchar(255)               NOT NULL,
    timezone          varchar(255) DEFAULT 'UTC' NOT NULL,
    locale            varchar(255) DEFAULT 'en'  NOT NULL,
    enabled           boolean      DEFAULT true  NOT NULL,
    created_at        timestamptz  DEFAULT now(),
    updated_at        timestamptz  DEFAULT now()
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_email_unique UNIQUE (email);