CREATE TABLE IF NOT EXISTS public.monitors
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             uuid         NOT NULL DEFAULT gen_random_uuid(),
    user_id          bigint,
    name             varchar(255) NOT NULL,
    description      text,
    enabled          boolean      NOT NULL DEFAULT true,
    monitorable_type varchar(255) NOT NULL,
    monitorable_id   bigint       NOT NULL,
    poll_interval       integer      NOT NULL,
    retry_interval   integer      NOT NULL,
    retry_max        integer      NOT NULL,
    deleted_at       timestamptz,
    created_at       timestamptz  DEFAULT now(),
    updated_at       timestamptz  DEFAULT now()
);

ALTER TABLE ONLY public.monitors
    ADD CONSTRAINT monitors_uuid_unique UNIQUE (uuid);

CREATE INDEX monitors_monitorable_idx
    ON public.monitors (monitorable_type, monitorable_id);

CREATE INDEX monitors_user_id_idx
    ON public.monitors (user_id);

ALTER TABLE ONLY public.monitors
    ADD CONSTRAINT monitors_user_id_fk
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;